export const LANGUAGE = {
  KR: "ko-KR",
  US: "en-US",
  AU: "en-AU",
  IN: "en-IN",
  GB: "en-GB",
};

export const VOICE_NAME = {
  "en-US": {
    CasualK: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Casual-K",
    },
    JourneyD: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Journey-D",
    },
    JourneyF: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Journey-F",
    },
    Neural2A: {
      gender: "남성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-A",
    },
    Neural2C: {
      gender: "여성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-C",
    },
    Neural2D: {
      gender: "남성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-D",
    },
    Neural2E: {
      gender: "여성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-E",
    },
    Neural2F: {
      gender: "여성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-F",
    },
    Neural2G: {
      gender: "여성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-G",
    },
    Neural2H: {
      gender: "여성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-H",
    },
    Neural2I: {
      gender: "남성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-I",
    },
    Neural2J: {
      gender: "남성",
      category: "Neural2",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Neural2-J",
    },
    NewsK: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-News-K",
    },
    NewsL: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-News-L",
    },
    NewsN: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-News-N",
    },
    Polyglot1: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Polyglot-1",
    },
    StandardA: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-A",
    },
    StandardB: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-B",
    },
    StandardC: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-C",
    },
    StandardD: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-D",
    },
    StandardE: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-E",
    },
    StandardF: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-F",
    },
    StandardG: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-G",
    },
    StandardH: {
      gender: "여성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-H",
    },
    StandardI: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-I",
    },
    StandardJ: {
      gender: "남성",
      category: "Standard",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Standard-J",
    },
    StudioO: {
      gender: "여성",
      category: "Studio",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Studio-O",
    },
    StudioQ: {
      gender: "남성",
      category: "Studio",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Studio-Q",
    },
    WaveNetA: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-A",
    },
    WaveNetB: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-B",
    },
    WaveNetC: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-C",
    },
    WaveNetD: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-D",
    },
    WaveNetE: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-E",
    },
    WaveNetF: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-F",
    },
    WaveNetG: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-G",
    },
    WaveNetH: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-H",
    },
    WaveNetI: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-I",
    },
    WaveNetJ: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(미국)",
      language_code: "en-US",
      voice_name: "en-US-Wavenet-J",
    },
  },
  "en-AU": {
    Neural2A: {
      gender: "여성",
      category: "Neural2",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Neural2-A",
    },
    Neural2B: {
      gender: "남성",
      category: "Neural2",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Neural2-B",
    },
    Neural2C: {
      gender: "여성",
      category: "Neural2",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Neural2-C",
    },
    Neural2D: {
      gender: "남성",
      category: "Neural2",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Neural2-D",
    },
    NewsE: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-News-E",
    },
    NewsF: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-News-F",
    },
    NewsG: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-News-G",
    },
    Polyglot1: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Polyglot-1",
    },
    StandardA: {
      gender: "여성",
      category: "Standard",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Standard-A",
    },
    StandardB: {
      gender: "남성",
      category: "Standard",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Standard-B",
    },
    StandardC: {
      gender: "여성",
      category: "Standard",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Standard-C",
    },
    StandardD: {
      gender: "남성",
      category: "Standard",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Standard-D",
    },
    WaveNetA: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Wavenet-A",
    },
    WaveNetB: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Wavenet-B",
    },
    WaveNetC: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Wavenet-C",
    },
    WaveNetD: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(오스트레일리아)",
      language_code: "en-AU",
      voice_name: "en-AU-Wavenet-D",
    },
  },
  "en-IN": {
    Neural2A: {
      gender: "여성",
      category: "Neural2",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Neural2-A",
    },
    Neural2B: {
      gender: "남성",
      category: "Neural2",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Neural2-B",
    },
    Neural2C: {
      gender: "남성",
      category: "Neural2",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Neural2-C",
    },
    Neural2D: {
      gender: "여성",
      category: "Neural2",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Neural2-D",
    },
    StandardA: {
      gender: "여성",
      category: "Standard",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Standard-A",
    },
    StandardB: {
      gender: "남성",
      category: "Standard",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Standard-B",
    },
    StandardC: {
      gender: "남성",
      category: "Standard",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Standard-C",
    },
    StandardD: {
      gender: "여성",
      category: "Standard",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Standard-D",
    },
    WaveNetA: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Wavenet-A",
    },
    WaveNetB: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Wavenet-B",
    },
    WaveNetC: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Wavenet-C",
    },
    WaveNetD: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(인도)",
      language_code: "en-IN",
      voice_name: "en-IN-Wavenet-D",
    },
  },
  "en-GB": {
    Neural2A: {
      gender: "여성",
      category: "Neural2",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Neural2-A",
    },
    Neural2B: {
      gender: "남성",
      category: "Neural2",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Neural2-B",
    },
    Neural2C: {
      gender: "여성",
      category: "Neural2",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Neural2-C",
    },
    Neural2D: {
      gender: "남성",
      category: "Neural2",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Neural2-D",
    },
    Neural2F: {
      gender: "여성",
      category: "Neural2",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Neural2-F",
    },
    NewsG: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-G",
    },
    NewsH: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-H",
    },
    NewsI: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-I",
    },
    NewsJ: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-J",
    },
    NewsK: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-K",
    },
    NewsL: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-L",
    },
    NewsM: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-News-M",
    },
    StandardA: {
      gender: "여성",
      category: "Standard",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Standard-A",
    },
    StandardB: {
      gender: "남성",
      category: "Standard",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Standard-B",
    },
    StandardC: {
      gender: "여성",
      category: "Standard",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Standard-C",
    },
    StandardD: {
      gender: "남성",
      category: "Standard",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Standard-D",
    },
    StandardF: {
      gender: "여성",
      category: "Standard",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Standard-F",
    },
    StudioB: {
      gender: "남성",
      category: "Studio",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Studio-B",
    },
    StudioC: {
      gender: "여성",
      category: "Studio",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Studio-C",
    },
    WaveNetA: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Wavenet-A",
    },
    WaveNetB: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Wavenet-B",
    },
    WaveNetC: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Wavenet-C",
    },
    WaveNetD: {
      gender: "남성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Wavenet-D",
    },
    WaveNetF: {
      gender: "여성",
      category: "WaveNet",
      language: "영어(영국)",
      language_code: "en-GB",
      voice_name: "en-GB-Wavenet-F",
    },
  },
};

export const SPEED = {
  "0.25": 0.25,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
};

export const PITCH = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11,
  12: 12,
  13: 13,
  14: 14,
  15: 15,
  16: 16,
  17: 17,
  18: 18,
  19: 19,
  20: 20,
};
